// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseFrontLeft;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseFrontRight;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseBackLeft;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseBackRight;
std::shared_ptr<frc::RobotDrive> RobotMap::driveBaseRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    driveBaseFrontLeft.reset(new WPI_TalonSRX(1));
    
    
    driveBaseFrontRight.reset(new WPI_TalonSRX(3));
    
    
    driveBaseBackLeft.reset(new WPI_TalonSRX(0));
    
    
    driveBaseBackRight.reset(new WPI_TalonSRX(2));
    
    
    driveBaseRobotDrive.reset(new frc::RobotDrive(driveBaseFrontLeft, driveBaseBackLeft,
              driveBaseFrontRight, driveBaseBackRight));
    
    driveBaseRobotDrive->SetSafetyEnabled(false);
        driveBaseRobotDrive->SetExpiration(0.1);
        driveBaseRobotDrive->SetSensitivity(0.5);
        driveBaseRobotDrive->SetMaxOutput(1.0);



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
